org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
kotlin.code.style=official

# plugin meta
pluginVersion=2.3.0
versionChannel=release

# dependencies
paperVersion=1.21.11-R0.1-SNAPSHOT
cloudVersion=2.0.0-beta.17
langchain4jVersion=1.18.0
jmhVersion=1.37
guavaVersion=33.4.0-jre
javaWebSocketVersion=1.6.0
