org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
kotlin.code.style=official

# plugin meta
pluginVersion=2.1.0
versionChannel=release

# dependencies
paperVersion=1.21.11-R0.1-SNAPSHOT
cloudVersion=2.0.0-beta.15
langchain4jVersion=1.16.3
jmhVersion=1.37
caffeineVersion=3.2.4
hikariCPVersion=7.1.0
guavaVersion=33.4.0-jre
